/**
 * Seed Function
 * (sails.config.bootstrap)
 *
 * A function that runs just before your Sails app gets lifted.
 * > Need more flexibility?  You can also create a hook.
 *
 * For more information on seeding your app with fake data, check out:
 * https://sailsjs.com/config/bootstrap
 */

module.exports.bootstrap = async function() {

  // By convention, this is a good place to set up fake data during development.
  //
  // For example:
  // ```
  // // Set up fake development data (or if we already have some, avast)
   if (await Coffee.count() > 0) {
     return;
   }

   await Coffee.createEach([
    {
      "name": "Beach Brew",
      "price": 8.99,
      "description": "Smooth coffee blend perfect for a relaxing beach day.",
      "caffeineContent": 150.50,
      "brand": "Tchibo",
      "roastDegree": "Light roast",
      "beanType": "Arabica",
      "certificates": ["UTZ Certified"],
      "origin": "South-America",
      "grindType": "Medium"
    },
    {
      "name": "Forest Aroma",
      "price": 10.50,
      "description": "Aromatic coffee with earthy tones from the rainforest.",
      "caffeineContent": 120.25,
      "brand": "Jacobs",
      "roastDegree": "Medium roast",
      "beanType": "Arabica",
      "certificates": ["Rainforest Alliance Certified"],
      "origin": "Africa",
      "grindType": "Whole bean"
    },
    {
      "name": "Sunrise Delight",
      "price": 12.75,
      "description": "Bright and cheerful coffee to kickstart your morning.",
      "caffeineContent": 130.00,
      "brand": "Mellitta",
      "roastDegree": "Medium-dark roast",
      "beanType": "Robusta",
      "certificates": ["Fair Trade Certified"],
      "origin": "Asia",
      "grindType": "Medium-coarse"
    },
    {
      "name": "Mountain Roast",
      "price": 15.99,
      "description": "Bold and strong coffee with rich flavor.",
      "caffeineContent": 180.00,
      "brand": "Eduscho",
      "roastDegree": "Dark roast",
      "beanType": "Robusta",
      "certificates": ["Direct Trade"],
      "origin": "North-America",
      "grindType": "Fine"
    },
    {
      "name": "Sunset Blend",
      "price": 9.99,
      "description": "Perfect coffee for a peaceful evening with mild flavors.",
      "caffeineContent": 110.50,
      "brand": "Tchibo",
      "roastDegree": "Light roast",
      "beanType": "Robusta",
      "certificates": ["Bird-Friendly"],
      "origin": "Australia",
      "grindType": "Extra fine"
    },
    {
      "name": "Rainforest Gold",
      "price": 13.25,
      "description": "A sustainable coffee option with rich undertones.",
      "caffeineContent": 140.30,
      "brand": "Jacobs",
      "roastDegree": "Medium roast",
      "beanType": "Lieberica",
      "certificates": ["Rainforest Alliance Certified", "Fair Trade Certified"],
      "origin": "South-America",
      "grindType": "Medium"
    },
    {
      "name": "Urban Espresso",
      "price": 11.75,
      "description": "Strong espresso with intense flavor for urban coffee lovers.",
      "caffeineContent": 190.00,
      "brand": "Mellitta",
      "roastDegree": "Dark roast",
      "beanType": "Lieberica",
      "certificates": ["Direct Trade"],
      "origin": "Europe",
      "grindType": "Fine"
    },
    {
      "name": "Jungle Breeze",
      "price": 7.99,
      "description": "Smooth coffee with a hint of freshness from jungle beans.",
      "caffeineContent": 125.20,
      "brand": "Eduscho",
      "roastDegree": "Light roast",
      "beanType": "Lieberica",
      "certificates": ["Fair Trade Certified"],
      "origin": "Africa",
      "grindType": "Coarse"
    },
    {
      "name": "Morning Sun",
      "price": 9.50,
      "description": "Medium-bodied coffee ideal for early risers.",
      "caffeineContent": 145.50,
      "brand": "Tchibo",
      "roastDegree": "Medium roast",
      "beanType": "Excelsa",
      "certificates": ["UTZ Certified", "Bird-Friendly"],
      "origin": "Asia",
      "grindType": "Medium"
    },
    {
      "name": "Twilight Brew",
      "price": 16.50,
      "description": "A luxurious coffee blend for late-night indulgence.",
      "caffeineContent": 160.00,
      "brand": "Jacobs",
      "roastDegree": "Medium-dark roast",
      "beanType": "Excelsa",
      "certificates": ["Rainforest Alliance Certified", "Direct Trade"],
      "origin": "North-America",
      "grindType": "Whole bean"
    },
    {
      name: "Crisp Morning Blend",
      price: 10.75,
      description: "A refreshing blend to start your day with energy.",
      caffeineContent: 135.5,
      brand: "Tchibo",
      roastDegree: "Light roast",
      beanType: "Arabica",
      certificates: ["UTZ Certified", "Fair Trade Certified"],
      origin: "Asia",
      grindType: "Whole bean",
    },
    {
      name: "Rainforest Sunrise",
      price: 12.25,
      description: "Eco-friendly coffee with a smooth and fruity flavor.",
      caffeineContent: 150.0,
      brand: "Jacobs",
      roastDegree: "Medium roast",
      beanType: "Robusta",
      certificates: ["Rainforest Alliance Certified"],
      origin: "South-America",
      grindType: "Medium-coarse",
    },
    {
      name: "Golden Afternoon",
      price: 11.5,
      description: "Perfect coffee for a relaxing afternoon.",
      caffeineContent: 120.0,
      brand: "Mellitta",
      roastDegree: "Medium-dark roast",
      beanType: "Excelsa",
      certificates: ["Direct Trade"],
      origin: "Europe",
      grindType: "Fine",
    },
    {
      name: "Velvet Night",
      price: 15.99,
      description: "A luxurious coffee for quiet evenings.",
      caffeineContent: 140.5,
      brand: "Eduscho",
      roastDegree: "Dark roast",
      beanType: "Arabica",
      certificates: ["Bird-Friendly"],
      origin: "North-America",
      grindType: "Extra fine",
    },
    {
      name: "Espresso Classic",
      price: 8.99,
      description: "Rich and strong espresso for true coffee lovers.",
      caffeineContent: 200.0,
      brand: "Mellitta",
      roastDegree: "Dark roast",
      beanType: "Robusta",
      certificates: ["Fair Trade Certified"],
      origin: "Africa",
      grindType: "Fine",
    },
    {
      name: "Tropical Delight",
      price: 13.5,
      description: "A fruity and vibrant blend from tropical regions.",
      caffeineContent: 155.3,
      brand: "Jacobs",
      roastDegree: "Medium roast",
      beanType: "Lieberica",
      certificates: ["UTZ Certified", "Direct Trade"],
      origin: "Australia",
      grindType: "Coarse",
    },
    {
      name: "Dark Mist",
      price: 9.75,
      description: "A smoky, bold coffee with an intense aroma.",
      caffeineContent: 175.0,
      brand: "Tchibo",
      roastDegree: "Medium-dark roast",
      beanType: "Robusta",
      certificates: ["Rainforest Alliance Certified"],
      origin: "South-America",
      grindType: "Medium",
    },
    {
      name: "Cocoa Bean Supreme",
      price: 14.5,
      description: "Hints of cocoa and smooth undertones for chocolate lovers.",
      caffeineContent: 160.0,
      brand: "Eduscho",
      roastDegree: "Light roast",
      beanType: "Excelsa",
      certificates: ["Fair Trade Certified"],
      origin: "Asia",
      grindType: "Whole bean",
    },
    {
      name: "Ocean Breeze Espresso",
      price: 10.99,
      description: "A refreshing and strong espresso to invigorate your day.",
      caffeineContent: 190.5,
      brand: "Jacobs",
      roastDegree: "Dark roast",
      beanType: "Lieberica",
      certificates: ["Bird-Friendly"],
      origin: "Europe",
      grindType: "Extra fine",
    },
    {
      name: "Golden Reserve",
      price: 17.5,
      description: "The finest coffee blend with a premium taste.",
      caffeineContent: 145.0,
      brand: "Mellitta",
      roastDegree: "Medium roast",
      beanType: "Arabica",
      certificates: ["Rainforest Alliance Certified"],
      origin: "North-America",
      grindType: "Medium-coarse",
    },
    {
      name: "Savanna Breeze",
      price: 8.5,
      description: "Smooth and mild coffee with earthy tones.",
      caffeineContent: 110.0,
      brand: "Tchibo",
      roastDegree: "Light roast",
      beanType: "Arabica",
      certificates: ["UTZ Certified"],
      origin: "Africa",
      grindType: "Coarse",
    },
    {
      name: "French Velvet",
      price: 11.99,
      description: "French-inspired coffee blend with a silky finish.",
      caffeineContent: 155.0,
      brand: "Eduscho",
      roastDegree: "Medium-dark roast",
      beanType: "Robusta",
      certificates: ["Fair Trade Certified", "Direct Trade"],
      origin: "Europe",
      grindType: "Medium",
    },
    {
      name: "Morning Bliss",
      price: 9.99,
      description: "A gentle start to brighten your morning.",
      caffeineContent: 120.0,
      brand: "Tchibo",
      roastDegree: "Light roast",
      beanType: "Arabica",
      certificates: ["UTZ Certified"],
      origin: "South-America",
      grindType: "Medium",
    },
    {
      name: "Mountain Aroma",
      price: 14.25,
      description: "Strong aroma from the highest mountains.",
      caffeineContent: 180.5,
      brand: "Jacobs",
      roastDegree: "Dark roast",
      beanType: "Robusta",
      certificates: ["Direct Trade"],
      origin: "North-America",
      grindType: "Fine",
    },
    {
      name: "Tropical Fusion",
      price: 11.5,
      description: "Exotic coffee with fruity notes.",
      caffeineContent: 150.0,
      brand: "Mellitta",
      roastDegree: "Medium roast",
      beanType: "Lieberica",
      certificates: ["Fair Trade Certified"],
      origin: "Australia",
      grindType: "Coarse",
    },
    {
      name: "Wild Espresso",
      price: 13.75,
      description: "Rich espresso with bold flavor.",
      caffeineContent: 200.0,
      brand: "Eduscho",
      roastDegree: "Dark roast",
      beanType: "Excelsa",
      certificates: ["Bird-Friendly"],
      origin: "Africa",
      grindType: "Extra fine",
    },
    {
      name: "Rainforest Reserve",
      price: 12.99,
      description: "Sustainably sourced coffee from rainforests.",
      caffeineContent: 140.0,
      brand: "Jacobs",
      roastDegree: "Medium-dark roast",
      beanType: "Robusta",
      certificates: ["Rainforest Alliance Certified"],
      origin: "South-America",
      grindType: "Whole bean",
    },
    {
      name: "Velvet Mornings",
      price: 10.5,
      description: "Smooth and silky coffee perfect for mornings.",
      caffeineContent: 130.0,
      brand: "Tchibo",
      roastDegree: "Light roast",
      beanType: "Arabica",
      certificates: ["UTZ Certified"],
      origin: "Asia",
      grindType: "Medium-coarse",
    },
    {
      name: "Golden Daylight",
      price: 15.0,
      description: "Premium coffee for a luxurious day.",
      caffeineContent: 170.0,
      brand: "Mellitta",
      roastDegree: "Medium roast",
      beanType: "Robusta",
      certificates: ["Fair Trade Certified", "Direct Trade"],
      origin: "North-America",
      grindType: "Fine",
    },
    {
      name: "Forest Symphony",
      price: 8.75,
      description: "Earthy coffee from the heart of the forest.",
      caffeineContent: 125.0,
      brand: "Eduscho",
      roastDegree: "Medium roast",
      beanType: "Arabica",
      certificates: ["Rainforest Alliance Certified"],
      origin: "Africa",
      grindType: "Coarse",
    },
    {
      name: "Urban Bliss",
      price: 16.5,
      description: "A smooth and elegant urban coffee.",
      caffeineContent: 185.0,
      brand: "Jacobs",
      roastDegree: "Dark roast",
      beanType: "Excelsa",
      certificates: ["Direct Trade"],
      origin: "Europe",
      grindType: "Whole bean",
    },
    {
      name: "Evening Elegance",
      price: 12.0,
      description: "Perfect blend for peaceful evenings.",
      caffeineContent: 110.0,
      brand: "Tchibo",
      roastDegree: "Light roast",
      beanType: "Lieberica",
      certificates: ["UTZ Certified", "Bird-Friendly"],
      origin: "Australia",
      grindType: "Medium",
    },
    {
      name: "Sunset Gold",
      price: 10.99,
      description: "Mild and smooth for relaxed moments.",
      caffeineContent: 120.5,
      brand: "Jacobs",
      roastDegree: "Medium roast",
      beanType: "Arabica",
      certificates: ["Fair Trade Certified"],
      origin: "South-America",
      grindType: "Medium-coarse",
    },
    {
      name: "Espresso Bold",
      price: 14.75,
      description: "Powerful espresso to keep you going.",
      caffeineContent: 200.0,
      brand: "Eduscho",
      roastDegree: "Dark roast",
      beanType: "Robusta",
      certificates: ["Direct Trade"],
      origin: "North-America",
      grindType: "Extra fine",
    },
    {
      name: "Night Serenade",
      price: 13.5,
      description: "A rich coffee with a smooth finish.",
      caffeineContent: 150.5,
      brand: "Mellitta",
      roastDegree: "Medium-dark roast",
      beanType: "Excelsa",
      certificates: ["Bird-Friendly"],
      origin: "Europe",
      grindType: "Fine",
    },
    {
      name: "Alpine Morning",
      price: 11.25,
      description: "Clean and crisp, inspired by alpine mornings.",
      caffeineContent: 135.0,
      brand: "Tchibo",
      roastDegree: "Light roast",
      beanType: "Arabica",
      certificates: ["Rainforest Alliance Certified"],
      origin: "Asia",
      grindType: "Medium",
    },
    {
      name: "Coastal Breeze",
      price: 9.5,
      description: "A refreshing blend from coastal regions.",
      caffeineContent: 125.0,
      brand: "Jacobs",
      roastDegree: "Medium roast",
      beanType: "Robusta",
      certificates: ["UTZ Certified"],
      origin: "Australia",
      grindType: "Coarse",
    },
  ]);
  
  await Category.createEach([
    {
      "name": "Whole Beans - Espresso Roast",
      "description": "Premium whole beans roasted for a bold and intense espresso flavor.",
      "location": "1"
    },
    {
      "name": "Whole Beans - Light Roast",
      "description": "Smooth and bright whole beans with a light roast, perfect for pour-over coffee.",
      "location": "2"
    },
    {
      "name": "Whole Beans - Dark Roast",
      "description": "Rich and smoky whole beans roasted to a dark perfection for intense coffee lovers.",
      "location": "3"
    },
    {
      "name": "Ground Coffee - Medium Grind",
      "description": "Finely ground coffee ideal for drip coffee machines and pour-over brewing.",
      "location": "4"
    },
    {
      "name": "Ground Coffee - Coarse Grind",
      "description": "Perfectly coarse ground coffee for French presses and cold brews.",
      "location": "5"
    },
    {
      "name": "Ground Coffee - Espresso Grind",
      "description": "Ultra-fine ground coffee for espresso machines, delivering rich crema.",
      "location": "6"
    },
    {
      "name": "Coffee Pods - Classic Roast",
      "description": "Convenient coffee pods with a balanced and classic roast for daily enjoyment.",
      "location": "7"
    },
    {
      "name": "Coffee Pods - Dark Roast",
      "description": "Single-serve pods with bold and dark roasted coffee for strong coffee lovers.",
      "location": "8"
    },
    {
      "name": "Coffee Pods - Decaf",
      "description": "Delicious decaffeinated coffee pods, perfect for evening brews.",
      "location": "9"
    },
    {
      "name": "Coffee Pods - Caramel Flavor",
      "description": "Flavored coffee pods with a sweet caramel touch for a delightful cup.",
      "location": "10"
    }
  ]);
  
};
